//
// --------------------------------------------------------------------------
//  Gurux Ltd
// 
//
//
// Filename:        $HeadURL$
//
// Version:         $Revision$,
//                  $Date$
//                  $Author$
//
// Copyright (c) Gurux Ltd
//
//---------------------------------------------------------------------------
//
//  DESCRIPTION
//
// This file is a part of Gurux Device Framework.
//
// Gurux Device Framework is Open Source software; you can redistribute it
// and/or modify it under the terms of the GNU General Public License 
// as published by the Free Software Foundation; version 2 of the License.
// Gurux Device Framework is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of 
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
// See the GNU General Public License for more details.
//
// This code is licensed under the GNU General Public License v2. 
// Full text may be retrieved at http://www.gnu.org/licenses/gpl-2.0.txt
//---------------------------------------------------------------------------

package gurux.terminal;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;

/**
 * SMS settings dialog.
 */
class GXSettings extends javax.swing.JDialog implements ActionListener {
    boolean Accepted;
    GXTerminal Target;
    /**
     * Creates new form GXSettings
     */
    @SuppressWarnings("unchecked")
    public GXSettings(java.awt.Frame parent, boolean modal, GXTerminal comp) {
        super(parent, modal);        
        super.setLocationRelativeTo(parent); 
        initComponents();                 
        Target = comp;
        String[] ports = GXTerminal.getPortNames();
        PortCB.setModel(new DefaultComboBoxModel(ports));
        int[] rates = GXTerminal.getAvailableBaudRates(null);
        BaudRate.setModel(new DefaultComboBoxModel(getStrings(rates)));
        int[] dataBits = new int[]{7, 8};
        DataBits.setModel(new DefaultComboBoxModel(getStrings(dataBits)));        
        String[] parity = new String[]{"None", "Odd", "Even", "Mark", "Space"};
        Parity.setModel(new DefaultComboBoxModel(parity));               
        String[] stopBits = new String[]{"One", "One_Point_Five", "Two"};
        StopBits.setModel(new DefaultComboBoxModel(stopBits));                 
        PhoneNumberTB.setText(Target.m_PhoneNumber);
        this.PINCodeTB.setText(Target.m_PIN);
        this.PortCB.setSelectedItem(Target.m_PortName);
        this.BaudRate.setSelectedItem(String.valueOf(Target.m_BaudRate));
        this.DataBits.setSelectedItem(String.valueOf(Target.m_DataBits));        
        this.Parity.setSelectedItem(findParity(Target.m_Parity));        
        this.StopBits.setSelectedItem(findStopBit(Target.m_StopBits));        
    }
            
    /*
     * If user press ESC.
     */
    @Override
    public void actionPerformed(ActionEvent e) {        
        this.dispose();
    }
    
    final String findStopBit(gurux.io.StopBits stopBits)
    {
        switch(stopBits)
        {
            case ONE:
                return "One";
            case TWO:
                return "Two";
            case ONE_POINT_FIVE:
                return "One_Point_Five";
        }
        return "";
    }
    final String findParity(gurux.io.Parity parity)
    {
        switch(parity)
        {
            case NONE:
                return "None";
            case ODD:
                return "Odd";
            case EVEN:
                return "Even";
            case MARK:
                return "Mark";
            case SPACE:
                return "Space";
        }
        return "";
    }
    
    final String[] getStrings(int[] list)
    {
        String[] tmp = new String[list.length];
        int pos = 0;
        for(int it : list)
        {
            tmp[pos] = String.valueOf(it);
            ++pos;
        }
        return tmp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PhoneNumberPanel = new javax.swing.JPanel();
        PhoneNumberLbl = new javax.swing.JLabel();
        PhoneNumberTB = new javax.swing.JTextField();
        PINCodePanel = new javax.swing.JPanel();
        PhoneNumberLbl2 = new javax.swing.JLabel();
        PINCodeTB = new javax.swing.JTextField();
        PortPanel = new javax.swing.JPanel();
        PortLbl1 = new javax.swing.JLabel();
        PortCB = new javax.swing.JComboBox();
        BaudRatePanel = new javax.swing.JPanel();
        BaudRateLbl = new javax.swing.JLabel();
        BaudRate = new javax.swing.JComboBox();
        DataBitsPanel = new javax.swing.JPanel();
        DataBitsLbl = new javax.swing.JLabel();
        DataBits = new javax.swing.JComboBox();
        ParityPanel = new javax.swing.JPanel();
        ParityLbl = new javax.swing.JLabel();
        Parity = new javax.swing.JComboBox();
        StopBitsPanel = new javax.swing.JPanel();
        StopBitsLbl = new javax.swing.JLabel();
        StopBits = new javax.swing.JComboBox();
        OKBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PhoneNumberPanel.setPreferredSize(new java.awt.Dimension(298, 33));

        PhoneNumberLbl.setText("Phone Number:");

        javax.swing.GroupLayout PhoneNumberPanelLayout = new javax.swing.GroupLayout(PhoneNumberPanel);
        PhoneNumberPanel.setLayout(PhoneNumberPanelLayout);
        PhoneNumberPanelLayout.setHorizontalGroup(
            PhoneNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhoneNumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PhoneNumberLbl)
                .addGap(18, 18, 18)
                .addComponent(PhoneNumberTB, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PhoneNumberPanelLayout.setVerticalGroup(
            PhoneNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PhoneNumberPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PhoneNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberLbl)
                    .addComponent(PhoneNumberTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(367, 367, 367))
        );

        PINCodePanel.setPreferredSize(new java.awt.Dimension(298, 35));

        PhoneNumberLbl2.setText("PIN Code:");

        javax.swing.GroupLayout PINCodePanelLayout = new javax.swing.GroupLayout(PINCodePanel);
        PINCodePanel.setLayout(PINCodePanelLayout);
        PINCodePanelLayout.setHorizontalGroup(
            PINCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PINCodePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PhoneNumberLbl2)
                .addGap(41, 41, 41)
                .addComponent(PINCodeTB, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PINCodePanelLayout.setVerticalGroup(
            PINCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PINCodePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PINCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberLbl2)
                    .addComponent(PINCodeTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PortPanel.setPreferredSize(new java.awt.Dimension(298, 35));

        PortLbl1.setText("Port:");

        PortCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout PortPanelLayout = new javax.swing.GroupLayout(PortPanel);
        PortPanel.setLayout(PortPanelLayout);
        PortPanelLayout.setHorizontalGroup(
            PortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PortPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PortLbl1)
                .addGap(70, 70, 70)
                .addComponent(PortCB, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PortPanelLayout.setVerticalGroup(
            PortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PortPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PortLbl1)
                    .addComponent(PortCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BaudRatePanel.setPreferredSize(new java.awt.Dimension(218, 35));

        BaudRateLbl.setText("Baud Rate:");

        BaudRate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout BaudRatePanelLayout = new javax.swing.GroupLayout(BaudRatePanel);
        BaudRatePanel.setLayout(BaudRatePanelLayout);
        BaudRatePanelLayout.setHorizontalGroup(
            BaudRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaudRatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BaudRateLbl)
                .addGap(41, 41, 41)
                .addComponent(BaudRate, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BaudRatePanelLayout.setVerticalGroup(
            BaudRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BaudRatePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BaudRatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BaudRateLbl)
                    .addComponent(BaudRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        DataBitsPanel.setPreferredSize(new java.awt.Dimension(220, 35));

        DataBitsLbl.setText("Data Bits:");

        DataBits.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout DataBitsPanelLayout = new javax.swing.GroupLayout(DataBitsPanel);
        DataBitsPanel.setLayout(DataBitsPanelLayout);
        DataBitsPanelLayout.setHorizontalGroup(
            DataBitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataBitsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DataBitsLbl)
                .addGap(50, 50, 50)
                .addComponent(DataBits, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DataBitsPanelLayout.setVerticalGroup(
            DataBitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataBitsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DataBitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DataBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataBitsLbl))
                .addGap(14, 14, 14))
        );

        ParityPanel.setPreferredSize(new java.awt.Dimension(219, 35));

        ParityLbl.setText("Parity:");

        Parity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout ParityPanelLayout = new javax.swing.GroupLayout(ParityPanel);
        ParityPanel.setLayout(ParityPanelLayout);
        ParityPanelLayout.setHorizontalGroup(
            ParityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ParityLbl)
                .addGap(64, 64, 64)
                .addComponent(Parity, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ParityPanelLayout.setVerticalGroup(
            ParityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParityPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ParityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ParityLbl)
                    .addComponent(Parity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        StopBitsLbl.setText("Stop Bits:");

        StopBits.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout StopBitsPanelLayout = new javax.swing.GroupLayout(StopBitsPanel);
        StopBitsPanel.setLayout(StopBitsPanelLayout);
        StopBitsPanelLayout.setHorizontalGroup(
            StopBitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StopBitsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StopBitsLbl)
                .addGap(49, 49, 49)
                .addComponent(StopBits, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        StopBitsPanelLayout.setVerticalGroup(
            StopBitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StopBitsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(StopBitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StopBitsLbl)
                    .addComponent(StopBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PhoneNumberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
            .addComponent(PINCodePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
            .addComponent(PortPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
            .addComponent(BaudRatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
            .addComponent(DataBitsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
            .addComponent(ParityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(StopBitsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PhoneNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PINCodePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PortPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BaudRatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DataBitsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ParityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StopBitsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OKBtn.setText("OK");
        OKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKBtnActionPerformed(evt);
            }
        });

        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OKBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CancelBtn))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelBtn)
                    .addComponent(OKBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    @Override
    protected JRootPane createRootPane() {
        KeyStroke stroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        JRootPane rootPane = new JRootPane();
        rootPane.registerKeyboardAction(this, stroke, JComponent.WHEN_IN_FOCUSED_WINDOW);
        return rootPane;
    }
    
    /*
     * Accept changes.
     */            
    private void OKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKBtnActionPerformed
        try
        {
            Target.m_PhoneNumber = PhoneNumberTB.getText();
            Target.m_PIN = this.PINCodeTB.getText();
            Target.m_PortName = this.PortCB.getSelectedItem().toString();
            Target.m_BaudRate = Integer.parseInt(this.BaudRate.getSelectedItem().toString());
            Target.m_DataBits = Integer.parseInt(this.DataBits.getSelectedItem().toString());        
            Target.m_Parity = gurux.io.Parity.valueOf(this.Parity.getSelectedItem().toString().toUpperCase());        
            Target.m_StopBits = gurux.io.StopBits.valueOf(this.StopBits.getSelectedItem().toString().toUpperCase());        
            Accepted = true;        
            this.dispose();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_OKBtnActionPerformed

    /*
     * Discard changes.
     */
    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BaudRate;
    private javax.swing.JLabel BaudRateLbl;
    private javax.swing.JPanel BaudRatePanel;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JComboBox DataBits;
    private javax.swing.JLabel DataBitsLbl;
    private javax.swing.JPanel DataBitsPanel;
    private javax.swing.JButton OKBtn;
    private javax.swing.JPanel PINCodePanel;
    private javax.swing.JTextField PINCodeTB;
    private javax.swing.JComboBox Parity;
    private javax.swing.JLabel ParityLbl;
    private javax.swing.JPanel ParityPanel;
    private javax.swing.JLabel PhoneNumberLbl;
    private javax.swing.JLabel PhoneNumberLbl2;
    private javax.swing.JPanel PhoneNumberPanel;
    private javax.swing.JTextField PhoneNumberTB;
    private javax.swing.JComboBox PortCB;
    private javax.swing.JLabel PortLbl1;
    private javax.swing.JPanel PortPanel;
    private javax.swing.JComboBox StopBits;
    private javax.swing.JLabel StopBitsLbl;
    private javax.swing.JPanel StopBitsPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
